# Generated by Django 3.1.4 on 2020-12-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsetting',
            name='user',
            field=models.ImageField(blank=True, null=True, upload_to='icon/'),
        ),
    ]
